# Generated by Django 5.0.6 on 2025-02-22 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('t', 'transgender')], max_length=1)),
                ('specialization_in', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('math', 'Mathematcis'), ('Bio', 'Biology'), ('Chem', 'Chemistry'), ('phy', 'physics'), ('Comp', 'Computer'), ('Art', 'Art'), ('Com', 'Commerce'), ('Geo', 'Geography'), ('PSci', 'Political Sciecne'), ('Env', 'Environment'), ('Soc', 'Social'), ('Hs', 'History')], max_length=15)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(max_length=64)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
