# Generated by Django 5.0.6 on 2025-02-22 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalBoard',
            fields=[
                ('education_Board_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'EducationalBoard',
            },
        ),
        migrations.CreateModel(
            name='EducationalYear',
            fields=[
                ('education_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'EducationalYear',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('Exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('exam_type', models.CharField(max_length=32)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Exam',
            },
        ),
    ]
