# Generated by Django 5.0.6 on 2025-02-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='queryrequest',
            name='subject',
        ),
    ]
