# Generated by Django 5.0.6 on 2025-02-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_queryrequest_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryrequest',
            name='types',
        ),
    ]
