# Generated by Django 5.0.6 on 2025-02-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_remove_queryrequest_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='subject',
        ),
    ]
