# Generated by Django 5.0.6 on 2025-02-22 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_', '0001_initial'),
        ('teacher', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('student_class', models.CharField(choices=[('P', 'Pre_Nursury'), ('N', 'Nursury'), ('KG', 'KinderGarten'), ('1', 'Class-1'), ('2', 'Class-3'), ('4', 'Class-4'), ('5', 'Class-5'), ('6', 'Class-6'), ('7', 'Class-7'), ('8', 'Class-8'), ('9', 'Class-9'), ('10', 'Class-10'), ('11', 'Class-11'), ('12', 'Class-12')], max_length=5)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DF', 'DRAFT'), ('PB', 'PUBLISHED')], max_length=2)),
                ('educational_Board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_.educationalboard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_.educationalyear')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('mother_name', models.CharField(max_length=64)),
                ('father_name', models.CharField(blank=True, max_length=64)),
                ('m_phone', models.CharField(blank=True, max_length=10)),
                ('f_phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=64, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=64)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('city', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'ParentInfo',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(default='', max_length=4)),
                ('submitted', models.CharField(default='', max_length=4)),
                ('balance', models.CharField(default='', max_length=4)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'fee',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_status', models.CharField(choices=[('a', 'absent'), ('p', 'present')], max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'Attendence',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_img', models.ImageField(blank=True, upload_to='')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('t', 'transgender')], max_length=1)),
                ('age', models.CharField(default=False, max_length=12)),
                ('gaurdian', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'StudentInfo',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('Hi1', 'Hindi-I'), ('Hi2', 'Hindi-II'), ('En1', 'English-Literature'), ('En2', 'English-Grammar'), ('M1', 'Math-I'), ('M2', 'Math-II'), ('Sci1', 'Science-I'), ('Sci2', 'Science-II'), ('Soc', 'Social Social'), ('Comp', 'Computer'), ('Geo', 'Geography'), ('GK', 'General-Konwledge'), ('Phy1', 'Physics'), ('Phy2', 'Physics-II'), ('Chem1', 'Chemistry-II')], max_length=20)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
