# Generated by Django 5.0.6 on 2025-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_attendence_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attendance_status',
            field=models.CharField(choices=[('p', 'present'), ('a', 'absent')], max_length=10),
        ),
    ]
