# Generated by Django 5.0.6 on 2025-02-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_attendence_attendance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
