# Generated by Django 5.0.6 on 2025-03-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_options_alter_studentinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='age',
            field=models.CharField(default='', max_length=12),
        ),
    ]
