# Generated by Django 5.0.6 on 2025-03-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_teacher_alter_studentinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attendance_status',
            field=models.CharField(choices=[('a', 'absent'), ('p', 'present')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('P', 'Pre_Nursury'), ('N', 'Nursury'), ('KG', 'KinderGarten'), ('1', 'Class-1'), ('2', 'Class-2'), ('3', 'Class-3'), ('4', 'Class-4'), ('5', 'Class-5'), ('6', 'Class-6'), ('7', 'Class-7'), ('8', 'Class-8'), ('9', 'Class-9'), ('10', 'Class-10'), ('11', 'Class-11'), ('12', 'Class-12')], max_length=5),
        ),
    ]
