# Generated by Django 5.0.6 on 2025-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_attendence_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('P', 'pre-nursury'), ('N', 'nursery'), ('KG', 'kg'), ('1', 'Class-1'), ('2', 'Class-2'), ('3', 'Class-3'), ('4', 'Class-4'), ('5', 'Class-5'), ('6', 'Class-6'), ('7', 'Class-7'), ('8', 'Class-8'), ('9', 'Class-9'), ('10', 'Class-10'), ('11', 'Class-11'), ('12', 'Class-12')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=32),
        ),
    ]
