# Generated by Django 5.0.6 on 2025-03-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_student_class_alter_subject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attendance_status',
            field=models.CharField(choices=[('a', 'absent'), ('p', 'present')], max_length=10),
        ),
    ]
