# Generated by Django 5.0.6 on 2025-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_attendence_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentinfo',
            name='f_phone',
        ),
        migrations.RemoveField(
            model_name='parentinfo',
            name='m_phone',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='parent_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='attendance_status',
            field=models.CharField(choices=[('p', 'present'), ('a', 'absent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='address',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='district',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='father_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='mother_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='postal_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='district',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gaurdian',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
